version: "3.4"
services:
  myapp:
    container_name: url_shortner
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '7000:7000'
    volumes:
      - ./:/usr/src/app
    command: yarn run dev
